# Generated by Django 5.2.1 on 2025-06-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_remove_uploadedimage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
