# Generated by Django 5.2.1 on 2025-06-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='party',
            new_name='party_affiliation',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='precinct',
            new_name='precinct_number',
        ),
        migrations.AlterField(
            model_name='voter',
            name='apartment_number',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v20state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21town',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v22general',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v23town',
            field=models.BooleanField(default=False),
        ),
    ]
