# Generated by Django 5.2.1 on 2025-06-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_url',
            new_name='image_file',
        ),
    ]
